export const defaultPageContents = [
  {
    slug: "home",
    label: "Home",
    path: "/",
    heroTitle: "Pioneering Energy Excellence",
    heroSubtitle: "Engineering, construction and energy infrastructure services for oil, gas, power, LPG and industrial projects in Bangladesh.",
    heroImageUrl: "/banner/banner1.jpeg",
    introTitle: "Pioneering Energy Excellence",
    introBody: "The Royal Utilisation Services (Pvt.) Ltd, together with Sigma Construction Company, stands as a pioneer in Bangladesh's energy sector since 1977.",
    seoTitle: "RUSL | Home",
    seoDescription: "Engineering, construction and energy infrastructure services for oil, gas, power, LPG and industrial projects in Bangladesh.",
  },
  {
    slug: "at-a-glance",
    label: "At a Glance",
    path: "/at-a-glance",
    heroTitle: "At a Glance",
    heroSubtitle: "Quick operating profile of The Royal Utilisation Services since 1977.",
    heroImageUrl: "/banner/banner1.jpeg",
    introTitle: "Company Snapshot",
    introBody: "A concise overview of company profile, operating strength, leadership and contact details.",
    seoTitle: "RUSL | At a Glance",
    seoDescription: "Company profile and operating snapshot of The Royal Utilisation Services.",
  },
  {
    slug: "mission-vision",
    label: "Mission & Vision",
    path: "/mission-vision",
    heroTitle: "Mission Vision",
    heroSubtitle: "Driving excellence in energy infrastructure through quality, safety and innovation.",
    heroImageUrl: "/banner/banner1.jpeg",
    introTitle: "Our Purpose",
    introBody: "To deliver trusted, high-quality infrastructure services while building sustainable long-term client relationships.",
    seoTitle: "RUSL | Mission & Vision",
    seoDescription: "Mission, vision and values of The Royal Utilisation Services.",
  },
  {
    slug: "our-strength",
    label: "Our Strength",
    path: "/our-strength",
    heroTitle: "Our Strength",
    heroSubtitle: "Experienced leadership, certified teams, modern equipment and proven delivery capability.",
    heroImageUrl: "/banner/banner1.jpeg",
    introTitle: "Built for Reliable Delivery",
    introBody: "Our strength comes from people, systems, equipment and a disciplined safety-first delivery culture.",
    seoTitle: "RUSL | Our Strength",
    seoDescription: "Management, technical staff, equipment and certification strength of RUSL.",
  },
  {
    slug: "preface",
    label: "Preface",
    path: "/preface",
    heroTitle: "Preface",
    heroSubtitle: "A company overview and introduction to RUSL's energy infrastructure journey.",
    heroImageUrl: "/banner/banner1.jpeg",
    introTitle: "Company Preface",
    introBody: "An introduction to our commitment, operating background and service capability.",
    seoTitle: "RUSL | Preface",
    seoDescription: "Company preface and introduction for The Royal Utilisation Services.",
  },
  {
    slug: "projects",
    label: "Projects",
    path: "/projects",
    heroTitle: "Projects",
    heroSubtitle: "Delivered, ongoing and upcoming references across energy and infrastructure sectors.",
    heroImageUrl: "/banner/banner1.jpeg",
    introTitle: "Project Portfolio",
    introBody: "Explore our work across oil, gas, power and energy infrastructure delivery.",
    seoTitle: "Projects | The Royal Utilisation Services",
    seoDescription: "Explore our portfolio of oil & gas, power sector, and energy infrastructure projects across Bangladesh.",
  },
  {
    slug: "team",
    label: "Team",
    path: "/team",
    heroTitle: "Meet Our Team",
    heroSubtitle: "Company people across core management, HR, accounts, engineering and operations.",
    heroImageUrl: "/banner/banner1.jpeg",
    introTitle: "Company People",
    introBody: "Meet the people behind our infrastructure delivery.",
    seoTitle: "RUSL | Team",
    seoDescription: "Meet the leadership and staff of The Royal Utilisation Services.",
  },
  {
    slug: "clients",
    label: "Clients",
    path: "/clients",
    heroTitle: "Clients",
    heroSubtitle: "Long-term partnerships with leading energy and infrastructure organizations.",
    heroImageUrl: "/banner/banner1.jpeg",
    introTitle: "Trusted Partnerships",
    introBody: "We work with leading organizations across energy, industrial and infrastructure sectors.",
    seoTitle: "RUSL | Clients",
    seoDescription: "Clients and partnerships of The Royal Utilisation Services.",
  },
  {
    slug: "certificates",
    label: "Certificates",
    path: "/certificates",
    heroTitle: "Certificates",
    heroSubtitle: "Compliance, certification and quality documents.",
    heroImageUrl: "/banner/banner1.jpeg",
    introTitle: "Certified Standards",
    introBody: "Our operating systems are backed by quality, safety and compliance credentials.",
    seoTitle: "RUSL | Certificates",
    seoDescription: "Certifications and compliance documents of The Royal Utilisation Services.",
  },
  {
    slug: "qhse-policy",
    label: "QHSE Policy",
    path: "/qhse-policy",
    heroTitle: "QHSE Policy",
    heroSubtitle: "Quality, health, safety and environmental commitments for every worksite.",
    heroImageUrl: "/banner/banner1.jpeg",
    introTitle: "QHSE Policy",
    introBody: "We are committed to the highest standards of Quality, Health, Safety, and Environment.",
    seoTitle: "RUSL | QHSE Policy",
    seoDescription: "Quality, health, safety and environment policy of The Royal Utilisation Services.",
  },
  {
    slug: "hytorc-about",
    label: "HYTORC About",
    path: "/hytorc/about",
    heroTitle: "HYTORC Solutions",
    heroSubtitle: "Torque tools, pumps, fasteners and accessories for industrial bolting.",
    heroImageUrl: "/banner/banner1.jpeg",
    introTitle: "HYTORC Solutions",
    introBody: "Industrial bolting solutions for demanding project environments.",
    seoTitle: "RUSL | HYTORC",
    seoDescription: "HYTORC tools, pumps, fasteners and accessories.",
  },
  {
    slug: "contact",
    label: "Contact",
    path: "/contact",
    heroTitle: "Contact",
    heroSubtitle: "Reach out for project inquiries, tender queries, support and office directions.",
    heroImageUrl: "/banner/banner1.jpeg",
    introTitle: "Feel free to reach out for project inquiries or support.",
    introBody: "Reach out to our team for consultation, tender queries, technical support, or office directions. We respond with clear next steps.",
    seoTitle: "RUSL | Contact",
    seoDescription: "Contact The Royal Utilisation Services for project inquiries and support.",
  },
];
